In [1]:
import numpy as np


In [2]:
##creating array from the list


In [3]:
arr=np.array([1,2,3,34,5])
print(" 1D array ",arr)

 1D array  [ 1  2  3 34  5]


In [4]:
arr1=np.array([1,2,23],[123,4,4,3])

TypeError: Field elements must be 2- or 3-tuples, got '123'

In [5]:
# this is beacause np.array() takes only one argument

In [7]:
arr1=np.array([[122,3,4,2,2,3],[3,3,4,4,44,7]])

In [8]:
print(arr1)

[[122   3   4   2   2   3]
 [  3   3   4   4  44   7]]


##Multiplication list vs array

In [9]:
l=[12,34,3]*2

In [10]:
print(l)

[12, 34, 3, 12, 34, 3]


In [11]:
arr1=arr1*2

In [12]:
print(arr1)

[[244   6   8   4   4   6]
 [  6   6   8   8  88  14]]


In [13]:
#which is faster list or array

In [23]:
import time
start=time.time()
l1=[i*2 for i in range(10000000)]
print("list time ",time.time()-start)

list time  0.48763084411621094


In [24]:
st=time.time()
arr=np.arange(10000000)*2
print(time.time()-st)

0.034787654876708984


creating array from the scratch

In [25]:
zeros=np.zeros((3,4))
print("zeros array \n",zeros)

zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
ones=np.ones((4,5))
print("ones array \n",ones)

ones array 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
full=np.full((4,5),8)
print("full array \n",full)

full array 
 [[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [28]:
sequence=np.arange(0,10,1)

In [29]:
print("sequence : \n",sequence)

sequence : 
 [0 1 2 3 4 5 6 7 8 9]


vector vs matric vs tensor

In [31]:
vec=np.array([3,4,5])
print("vector ",vec)

vector  [3 4 5]


In [32]:
mat=np.array([[1,2,3,],[1,2,2]])

In [33]:
print(mat)

[[1 2 3]
 [1 2 2]]


In [36]:
tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])

In [38]:
print("tensor",tensor )

tensor [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
# tensor is multi dimensional array

properties of array

In [41]:
vec.shape
tensor.shape

(2, 2, 3)

In [43]:
vec.ndim
tensor.ndim

3

In [49]:
mat.size # this give total number element present in the array
tensor.size

12

In [50]:
tensor.dtype

dtype('int64')

In [56]:
arr=np.arange(10)

In [57]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [70]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
arr.flatten() # return the copy flaten array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
arr.flat

In [75]:
arr.ravel()  #return the view of the array or original array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])