Numpy operation

In [2]:
import numpy as np
import random as rand


In [16]:
# slicing
arr=np.random.random(5)

In [17]:
print(arr)

[0.13192676 0.01622719 0.2860967  0.34603129 0.91174237]


In [18]:
arr[3]

0.3460312881153975

In [19]:
arr2d=np.random.randint(0,10,(2,4))

In [20]:
print(arr2d)

[[2 6 6 3]
 [0 2 0 9]]


In [23]:
arr2d[1][3]

9

In [24]:
    arr2d[1:2]

array([[0, 2, 0, 9]])

In [25]:
arr3=np.random.randint(0,12,(3,4))

In [26]:
print(arr3)

[[ 4  1  1  8]
 [ 1  7  5  9]
 [ 4  0 11  6]]


In [27]:
arr3[1 , 1:3]

array([7, 5])

In [28]:
# boolean indexing


In [29]:
arr4=np.arange(10)

In [30]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
temp=arr4[arr4%2==0]

In [32]:
temp


array([0, 2, 4, 6, 8])

In [35]:
arr4[[2,0,5,9]]

array([2, 0, 5, 9])

In [36]:
arr5=np.random.randint(0,20,(3,5))

In [37]:
arr5

array([[ 5, 10,  6, 16, 15],
       [ 6,  1, 16, 10, 15],
       [17,  2, 18, 10, 19]])

In [42]:
arr5[[1,0,2,1,1]]

array([[ 6,  1, 16, 10, 15],
       [ 5, 10,  6, 16, 15],
       [17,  2, 18, 10, 19],
       [ 6,  1, 16, 10, 15],
       [ 6,  1, 16, 10, 15]])

In [50]:
arr5

array([[ 5, 10,  6, 16, 15],
       [ 6,  1, 16, 10, 15],
       [17,  2, 18, 10, 19]])

In [43]:
# where clasue of np it is same as iternary eqution

In [53]:
temp1=np.where(arr5 > 5 ,arr5, 1)

In [54]:
temp1

array([[ 1, 10,  6, 16, 15],
       [ 6,  1, 16, 10, 15],
       [17,  1, 18, 10, 19]])

In [55]:
# adding value array

In [56]:
arr6=np.array([1,2,3,4,5])
arr7=np.array([1,2,3,4,5])

In [57]:
new_arr=arr6+arr7

In [58]:
new_arr

array([ 2,  4,  6,  8, 10])

In [60]:
new_arr=np.concatenate((arr6,arr7))

In [61]:
new_arr

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [62]:
#array compatibility

In [63]:
arr6.shape==arr7.shape

True

In [ ]:
# adding array using vstack

In [65]:
new1=np.vstack((arr6,arr7))

In [66]:
new1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [67]:
new2=np.hstack((arr6,arr7))

In [68]:
new2

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [74]:
new1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [69]:
# deleting the element

In [90]:
arr=np.delete(new1,4,1)

In [91]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])